# Generated by Django 6.0.3 on 2026-03-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
